services:
  - type: web
    name: n8n-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        sync: false
      - key: GENERIC_TIMEZONE
        value: UTC
      - key: N8N_SECURE_COOKIE
        value: false
      - key: N8N_METRICS
        value: true
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-postgres
          property: host
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-postgres
          property: database
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-postgres
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-postgres
          property: password
      - key: DB_POSTGRESDB_SSL
        value: true
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
    healthCheckPath: /healthz

databases:
  - name: n8n-postgres
    databaseName: n8n_db
    user: n8n_user
    plan: free
